/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ListRouteImport } from './routes/list'
import { Route as IndexAliasRouteImport } from './routes/index_'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as HomeRouteImport } from './routes/index'

const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexAliasRoute = IndexAliasRouteImport.update({
  id: '/index_',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeRoute
  '/admin': typeof AdminRoute
  '/explore': typeof ExploreRoute
  '/index': typeof IndexAliasRoute
  '/list': typeof ListRoute
}
export interface FileRoutesByTo {
  '/': typeof HomeRoute
  '/admin': typeof AdminRoute
  '/explore': typeof ExploreRoute
  '/index': typeof IndexAliasRoute
  '/list': typeof ListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof HomeRoute
  '/admin': typeof AdminRoute
  '/explore': typeof ExploreRoute
  '/index_': typeof IndexAliasRoute
  '/list': typeof ListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/explore' | '/index' | '/list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/explore' | '/index' | '/list'
  id: '__root__' | '/' | '/admin' | '/explore' | '/index_' | '/list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRoute
  AdminRoute: typeof AdminRoute
  ExploreRoute: typeof ExploreRoute
  IndexAliasRoute: typeof IndexAliasRoute
  ListRoute: typeof ListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index_': {
      id: '/index_'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof IndexAliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRoute,
  AdminRoute: AdminRoute,
  ExploreRoute: ExploreRoute,
  IndexAliasRoute: IndexAliasRoute,
  ListRoute: ListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
